KNOWLEDGE_UNSUPPORTED_VERSION = (
    "KNOWLEDGE_UNSUPPORTED_VERSION"
)

KNOWLEDGE_MISSING_PROJECT_ID = (
    "KNOWLEDGE_MISSING_PROJECT_ID"
)

KNOWLEDGE_DUPLICATE_FILE_ID = (
    "KNOWLEDGE_DUPLICATE_FILE_ID"
)

KNOWLEDGE_UNKNOWN_FILE_REFERENCE = (
    "KNOWLEDGE_UNKNOWN_FILE_REFERENCE"
)

KNOWLEDGE_UNKNOWN_SYMBOL_REFERENCE = (
    "KNOWLEDGE_UNKNOWN_SYMBOL_REFERENCE"
)

KNOWLEDGE_UNKNOWN_CHUNK_REFERENCE = (
    "KNOWLEDGE_UNKNOWN_CHUNK_REFERENCE"
)

KNOWLEDGE_INVALID_STRUCTURE = (
    "KNOWLEDGE_INVALID_STRUCTURE"
)

KNOWLEDGE_CORRUPTED_STATE = (
    "KNOWLEDGE_CORRUPTED_STATE"
)
